### ISSUE TITLE
Support "bin" files from Amazfit Band 7

### ISSUE THREAD

**Issue by cfgnunes** [melianmiko/zmake#1]
Hello!

It will be interesting if the Zmake uncompress the "bin" files from "Amazfit Band 7" watchfaces.

Best regards!

**Comment by melianmiko** [comment]
It already can do that.

Amazfit Band 7 uses the same watchface/app formats as Smart Band 7, so zmake will work with them.

**Comment by cfgnunes** [comment]
Hi, @melianmiko!

When I try to convert a file ".bin" to ".js", it result an error:

> Traceback (most recent call last):
  File "zmake/__main__.py", line 26, in <module>
  File "zmake/context.py", line 52, in perform_auto
  File "zmake/context.py", line 86, in process_bin
  File "zipfile.py", line 1267, in __init__
  File "zipfile.py", line 1334, in _RealGetContents
zipfile.BadZipFile: File is not a zip file
FAILED

See these examples below:
https://github.com/cfgnunes/tricarbon-watchface/blob/main/app/watchface/194x368_s_bari/index.bin
https://github.com/cfgnunes/tricarbon-watchface/blob/main/app/app.bin

**Comment by melianmiko** [comment]
Oh, now I understand.

That files aren't a watchface by itself, it's a compiled JavaScript code. For some reasons, some watchfaces uses a QuickJS bytecode files instead of plain JS scripts.

And this files can't be decompiled for now. Not only zmake, there's globally no way to decompile JS bytecode files.

Sorry, I can't help with that.

**Comment by cfgnunes** [comment]
Thanks for the information, @melianmiko! 😊
